### ISSUE TITLE
cargo: outdated 'as-slice' dependency

### ISSUE THREAD

**Issue by lucab** [japaric/aligned#14]
I was looking into duplicate/stale dependencies in one of my embedded projects, and it looks like some of those are coming from the fact that this crate uses an old `as-slice` 0.1 dependency instead of the latest 0.2 (in turn bringing in more duplicate/stale transitive dependencies).
Would it be possible to bump `as-slice` in the cargo manifest here? Additionally, those traits implementations seem to be re-exported by this crate, so I think a semver bump may be required too.

**Comment by japaric** [comment]
[0.4.0](https://crates.io/crates/aligned) depends on as-slice 0.2.x

**Comment by lucab** [comment]
@japaric thanks a lot for the prompt update! :green_heart:
